### ISSUE TITLE
There is a bug in file cdfbn2.f90

### ISSUE THREAD

**Issue by mitaolin2** [meom-group/CDFTOOLS#16]
In file cdfbn2.f90, there is no calculation for awk(:,:,idown), but it will be used to calculation the buoyancy frequency at T-grid.

**Comment by molines** [comment]
Hello,  you are right ( I have just added initialization of zwk(:,:,idown) )
should be OK now at  f25c586

**Comment by molines** [comment]
Sorry I meant fc48473

**Comment by mitaolin2** [comment]
Thanks a lot.
