### ISSUE TITLE
Is it a error in file cdfbn2.f90

### ISSUE THREAD

**Issue by mitaolin2** [meom-group/CDFTOOLS#24]
To whom it may concern,

When I try to use the cdfbn2 to calculate the buoyance frequency, I found it seems that an error when setting the values of ztemp(:,:,idown) and zsal(:,:,idown) as follows:
-----------------------------------------------------------------------------------------------
148      ztemp(:,:,idown) = getvar(cf_tfil, cn_votemper,  npk-1, npiglo, npjglo, ktime=jt)
149      zsal( :,:,idown) = getvar(cf_tfil, cn_vosaline,  npk-1, npiglo, npjglo, ktime=jt)
------------------------------------------------------------------------------------------------
Why always use the level about bottom to set them not change as the loop of vertical levels? It probably should be:
do jk = npk-1,2,-1
.....
ztemp(:,:,idown) = getvar(cf_tfil, cn_votemper,  jk-1, npiglo, npjglo, ktime=jt)
 zsal( :,:,idown) = getvar(cf_tfil, cn_vosaline,  jk-1, npiglo, npjglo, ktime=jt)
.....
end do

Best,
Libin Ma

**Comment by molines** [comment]
Hello! 

I double check the actual code for cdfbn2 and **all is OK**. You probably are using an old version of the code (because line 148 and 149 actually do not correspond to what they are).  (but looking at the log for this program I do not see any fix corresponding to

   The actual code looks like : 

        ztemp(:,:,idown) = getvar(cf_tfil, cn_votemper,  npk-1, npiglo, npjglo, ktime=jt)
        zsal( :,:,idown) = getvar(cf_sfil, cn_vosaline,  npk-1, npiglo, npjglo, ktime=jt)
        zwk(:,:,idown)   = 0.0
  
     DO jk = npk-1, 2, -1
        PRINT *,'level ',jk
        zmask(:,:)=1.
        ztemp(:,:,iup)= getvar(cf_tfil, cn_votemper, jk-1, npiglo, npjglo, ktime=jt)
        zsal(:,:,iup) = getvar(cf_sfil, cn_vosaline, jk-1, npiglo, npjglo, ktime=jt)
        WHERE(zsal(:,:,idown) == zsps ) zmask = 0

        IF ( lfull ) THEN ; e3w(:,:) = e3w1d(jk)
        ELSE              ; e3w(:,:) = getvar(cn_fe3w, cn_ve3w , jk, npiglo, npjglo, ktime=it, ldiom=.NOT.lg_vvl )
        ENDIF

        zwk(:,:,iup) = eosbn2(ztemp, zsal, gdep(jk), e3w, npiglo, npjglo ,iup, idown)* zmask(:,:)

        IF ( .NOT. l_w ) THEN
           ! now put zn2 at T level (k )
           WHERE ( zwk(:,:,idown) == 0 ) ; zn2(:,:) =  zwk(:,:,iup)
           ELSEWHERE                     ; zn2(:,:) = 0.5 * ( zwk(:,:,iup) + zwk(:,:,idown) ) * zmask(:,:)
           END WHERE
        ELSE
          zn2(:,:) = zwk(:,:,iup)
        ENDIF


The reading of level npk-1 is done for initialization. Then in the loop, jk-1 is used. And idown, iup are switched at the end of the loop.

So, no problems.

Cheers,
Jean-Marc
