### ISSUE TITLE
cdfvFWov

### ISSUE THREAD

**Issue by janharlass** [meom-group/CDFTOOLS#25]
cdfvFWov can't find correct mesh_mask section, which it explicitly asks for.
Needs further changes in cdfio.F90 to read e3v properly, see follow up issue.
FIX:
```diff --git a/src/cdfvFWov.f90 b/src/cdfvFWov.f90
index 53baab5..0a0b9bc 100644
--- a/src/cdfvFWov.f90
+++ b/src/cdfvFWov.f90
@@ -174,7 +174,12 @@ PROGRAM cdfvFWov
   rmaskn(:,:) = getvarxz(cf_mask, cn_tmask, kj=2,   kpi=npiglo, kpz=npk,    kimin=1, kkmin=1)
   rmaskv(:,:) = getvarxz(cf_mask, cn_vmask, kj=1,   kpi=npiglo, kpz=npk,    kimin=1, kkmin=1)
   de1v(:,:)   = getvar  (cf_hgr,  cn_ve1v,  klev=1, kpi=npiglo, kpj=npjglo, kimin=1, kjmin=1)
-  de3v(:,:)   = getvarxz(cn_fe3v, cn_ve3v,  kj=1,   kpi=npiglo, kpz=npk,    kimin=1, kkmin=1)
+
+! cn_fe3v points to "mesh_zgr.nc", but we explicitly ask for mesh_zgr
+  de3v(:,:)   = getvarxz(cf_zgr, cn_ve3v,  kj=1,   kpi=npiglo, kpz=npk,    kimin=1, kkmin=1)```

**Comment by willirath** [comment]
You can propose this change as a pull request by just editing it (click through the source and hit the little pen icon).  As you don't have write permissions in this repo, a fork and a pull request will be created automatically.

Short link to proposing the change: https://github.com/meom-group/CDFTOOLS/edit/master/src/cdfvFWov.f90#L177

**Comment by janharlass** [comment]
see #27 
[sorry - first time on github!]
